### ISSUE TITLE
State Minimum OkHttp Version for the Readme Example

### ISSUE THREAD

**Issue by TommyJ1994** [datatheorem/TrustKit-Android#22]
The example in the readme does not work with all versions of 3.x of OkHttp. 

This is because the deprecated sslSocketFactory function takes 2 parameters in newer versions of OkHttp 3.x, but in older versions of 3.x, it still uses only 1 parameter which won't work.

 https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#sslSocketFactory-javax.net.ssl.SSLSocketFactory-

Maybe we can update the example to state the minimum required OkHttp version?

**Comment by jobot0** [comment]
We chose to not write examples for OkHttp 3.1.x and 3.2.x because the method with only one parameter was deprecated. 
However TrustKit is working with these versions, the same way it does for the ones on the 2.x branch and the HttpUrlConnection example with `Trustkit.getInstance().getSSLSocketFactory(url)` alone.

**Comment by TommyJ1994** [comment]
@jobot0 Hi, yes I mean the following, in the code snippet in the readme, can you change. I lost a lot of time trying to get the readme example working with 3.2.0 as the comment just said `// OkHttp 3` so i presumed it was all 3.x versions it worked with.

```
  // OkHttp 3
  OkHttpClient client =
    ...
    .build();
```

to

```
  // OkHttp 3.3.x and Higher
  OkHttpClient client =
    ...
    .build();
```

**Comment by jobot0** [comment]
@TommyJ1994 Oh ok sorry about that. We'll add both ways on the next release to help people managing with older versions.
