### ISSUE TITLE
enforcePinning flag not working when set to false

### ISSUE THREAD

**Issue by tavo1985** [datatheorem/TrustKit-Android#43]
I have implemented TrustKit in my react-native app. I'm using TrustKit 1.1.0 and OkHttp 3.6.0.
When I set enforcePinning to false, TrustKit is still blocking the network connection when SSL Pinning validation fails. 
enforcePinning does not make any difference if set to true or false, TrustKit always blocks the network connection when SSL Pinning validation fails.

**Comment by tavo1985** [comment]
Any update on this issue?

**Comment by AbhishekCode** [comment]
Facing same issue. Using react-native.

**Comment by nabla-c0d3** [comment]
Hello,
Thanks for the report. There is a unit test to validate that enforcePinning does work (https://github.com/datatheorem/TrustKit-Android/blob/master/trustkit/src/androidTest/java/com/datatheorem/android/trustkit/pinning/SSLSocketFactoryTest.java#L278) so I think the issue here has to do with react-native. 
However, TrustKit does not officially support react-native (we've never tested it) so I'll close this issue.
Good luck!
